### ISSUE TITLE
No such app!

### ISSUE THREAD

**Issue by 0x73706f6f6b** [egggkim/whatshappenin#21]
Has this app been deleted from Heroku? Can't access.

**Comment by egggkim** [comment]
Hi Denis,

We took it down temporarily to put some more work into it as it wasn't quite up to our standards. I'll speak with my group mates and try to have a running version up for you to check out some time tomorrow. 

Best,
Karen

**Comment by egggkim** [comment]
Sorry about the confusion - it seems it was just a bad link in the original readme. The link has been updated and the current version of the project should now be accessible via Heroku.

**Comment by 0x73706f6f6b** [comment]
@egggkim Sounds good. Thanks!
